name: Bump Version
on:
  workflow_call:
    inputs:
      versionFile:
        type: string
        description: The path in the repo to the file that tracks the version-file
        required: true
    outputs:
      skipped:
        description: If a new release was skipped because there was no changes
        value: ${{ jobs.bumpVersion.outputs.skipped }}
      version:
        description: The new version
        value: ${{ jobs.bumpVersion.outputs.version }}
      tag:
        description: The new tag
        value: ${{ jobs.bumpVersion.outputs.tag }}
      cleanChangelog:
        description: The markdown changelog
        value: ${{ jobs.bumpVersion.outputs.cleanChangelog }}
      commitHash:
        description: The commit hash for the version bump commit
        value: ${{ jobs.bumpVersion.outputs.commitHash }}

jobs:
  bumpVersion:
    name: Bump Version
    runs-on: ubuntu-20.04
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      version: ${{ steps.changelog.outputs.version }}
      tag: ${{ steps.changelog.outputs.tag }}
      cleanChangelog: ${{ steps.changelog.outputs.clean_changelog }}
      commitHash: ${{ steps.commitHash.outputs.commitHash }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          ref: main
          fetch-depth: 0

      - name: Create Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: ${{ inputs.versionFile }}
          output-file: "false"

      - name: Get Commit Hash
        id: commitHash
        run: echo "::set-output name=commitHash::$(git rev-parse --verify HEAD)"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
